In [1]:
import numpy as np
data = np.load('../../datasets/n-subjettiness_data/test_all.npy')

In [53]:
data[:, 26]

array([1., 1., 1., ..., 0., 0., 0.])

In [54]:
col = abs(1-data[:, 26])[..., None]

In [17]:
new_arr = np.append(data, col, 1)

In [24]:
np.sum(new_arr[:, 27] + new_arr[:, 26])

399884.0

In [25]:
len(data)

399884

In [26]:
new_arr[:, [26, 27]] = new_arr[:, [27, 26]]

In [31]:
np.sum(new_arr[:,27] + new_arr[:,26])

399884.0

In [60]:
sig_col = data[:, 26][...,None]
bkg_col = abs(1-data[:, 26])[..., None]
labels = np.append(bkg_col, sig_col, 1)

In [48]:
labels.append(abs(1-data[:, 26])[..., None])

In [56]:
labels = np.append(data[:, 26][...,None], abs(1-data[:, 26])[..., None], 1)

In [58]:
labels[0]

array([1., 0.])

In [62]:
labels[0]

array([0., 1.])

In [64]:
n = np.delete(data.copy(), 26, 1)

In [70]:
n[:,25] - data[:,25]

array([0., 0., 0., ..., 0., 0., 0.])

In [71]:
data[:,26]

array([1., 1., 1., ..., 0., 0., 0.])

In [72]:
np.delete(data, 26, 1)

array([[5.47989947e-01, 4.59670009e-01, 1.24217101e+00, ...,
        2.81493263e-03, 5.65768434e+02, 1.81222097e+02],
       [5.07464740e-01, 2.77831261e-01, 1.11719334e-01, ...,
        3.21455136e-03, 5.72772056e+02, 1.77417944e+02],
       [3.88753164e-01, 2.23330322e-01, 1.10985922e-01, ...,
        2.21235616e-03, 5.60084384e+02, 1.61688688e+02],
       ...,
       [2.04131598e-01, 8.80766141e-02, 4.69655347e-02, ...,
        4.55570065e-03, 6.04801931e+02, 1.28999397e+02],
       [9.35790836e-01, 1.95296136e+00, 1.13088418e+01, ...,
        7.85950714e-03, 5.97214312e+02, 2.38697998e+02],
       [1.72080654e-01, 3.65728311e-02, 6.19351844e-03, ...,
        1.62341697e-03, 6.05563680e+02, 4.78349194e+01]])

In [2]:
if not False:
    print('hi')

hi


In [49]:
new_arr = data[:,0:24]

In [50]:
arr = np.append(new_arr, data[:,24:26], 1)

In [51]:
data[:,25]

array([181.22209735, 177.41794376, 161.68868817, ..., 128.99939685,
       238.69799797,  47.83491944])

In [52]:
arr[:,25]

array([181.22209735, 177.41794376, 161.68868817, ..., 128.99939685,
       238.69799797,  47.83491944])