In [36]:
import pandas as pd
import math 
import numpy as np
import glob
import sklearn
from sklearn.metrics import roc_curve
#Train data
# Read in hdf5 files
# Note: you will need to repeat this processing for input_filenames train, test and val

input_filename = "train"
%env HDF5_USE_FILE_LOCKING=FALSE
store = pd.HDFStore("../../datasets/"+input_filename+".h5")
df = store.select("table")

env: HDF5_USE_FILE_LOCKING=FALSE


In [37]:
len(df)

1211000

In [2]:
jets=np.array(df)
jets2=jets[:,0:800].reshape((len(jets),200,4))
# This way I'm getting the 1st 199 constituents.
# jets[:,800:804] is the constituent 200.
# jets[:,804] has a label=0 for train, 1 for test, 2 for val.
# jets[:,805] has the label sg/bg
#     print('jets2=',jets2[0])
labels=jets[:,805:806]
#     print('labels=',labels)
npy_jets=[]
for i in range(len(jets2)):
    # Get the index of non-zero entries
    nonzero_entries=jets2[i][~np.all(jets2[i] == 0, axis=1)]
    npy_jets.append([nonzero_entries,0 if labels[i] == 0 else 1])

In [31]:
len(range(1,9))

8

In [18]:
from dataset_pfn import PFNDataset
val_path = "../../datasets/val.h5"
df = mydataset = PFNDataset(val_path)

In [32]:
f,g,h = df[:]

In [33]:
len(f)

403000

In [20]:
import torch
m=g.reshape(-1,200,1)
torch.cat((m,m,m), dim=2)*f

tensor([[[ 4.2884e-01,  8.0703e-03, -2.8403e-03],
         [ 2.3426e-01,  7.7468e-03, -4.2367e-04],
         [ 1.2213e-01,  1.3394e-02,  3.0334e-03],
         ...,
         [ 0.0000e+00, -0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  0.0000e+00]],

        [[ 4.9001e-01, -3.9734e-02,  5.7028e-02],
         [ 1.3600e-01, -4.6183e-02,  1.4545e-01],
         [ 8.7929e-02, -3.7718e-02,  6.3676e-02],
         ...,
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00]],

        [[ 2.4543e-01,  4.6116e-01,  2.0200e-01],
         [ 8.7942e-02, -2.3502e-01, -2.1954e-01],
         [ 7.1707e-02, -1.9456e-01, -1.6406e-01],
         ...,
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -0.0000e+00]],

        ...,

        [[ 2.5809e-01, -1.9860e-01,  8

In [21]:
p=torch.cat((m,m,m), dim=2)
print(p.shape)

torch.Size([403000, 200, 3])


In [22]:
p[0]

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [13]:
x=torch.randn(500*200, 256)
torch.stack(torch.split(x.permute(1, 0), 200, dim=1), 0).shape

torch.Size([500, 256, 200])

In [19]:
g=g.reshape(-1, 1, 200)

In [21]:
g[0].shape

torch.Size([1, 200])

In [3]:
import pandas as pd
df_val = pd.read_pickle("../../datasets/topoprocessed/val.pkl")

In [4]:
import pandas as pd
df = pd.read_parquet('../../datasets/TopLandscape/val_file.parquet', engine='fastparquet')

In [5]:
df

label      jet_pt   jet_eta   jet_phi   jet_energy    jet_mass  \
0           0  566.683105  0.428453 -1.209822   620.194702   29.407429   
1           0  629.077393 -0.624132  1.248070   771.780029  157.048019   
2           0  571.624329 -0.618911  2.227797   721.285767  226.969543   
3           0  567.747498 -0.941343 -0.236163   843.982483   96.668243   
4           0  601.138611  0.272787 -1.111730   625.290039   45.342747   
...       ...         ...       ...       ...          ...         ...   
402994      1  559.554626  1.775505  2.092077  1712.989502  218.539474   
402995      1  629.255798  0.608431  2.028461   767.940186  167.880951   
402996      1  576.689819  1.676220  0.405522  1604.377930  171.015350   
402997      1  562.433350  0.266373 -2.030721   606.147949  167.639786   
402998      1  610.977234  0.152157 -2.561068   649.163452  198.521286   

        jet_nparticles                                            part_px  \
0                   20  [85.2275, 46.856384, 24.653267, 7.481191, 6.35...   
1                   41  [82.45904, 15.370172, 14.434706, 12.19732, 27....   
2                   43  [-108.09253, -21.669872, -19.73748, -28.543318...   
3                   71  [49.80525, 38.63646, 37.110703, 32.184956, 27....   
4                   19  [186.81108, 19.375856, 12.717323, 9.705414, 5....   
...                ...                                                ...   
402994              69  [-139.26302, -31.43379, -0.62545586, -2.130456...   
402995              58  [-107.87957, -37.67503, -32.266167, -16.149529...   
402996              51  [73.916145, 67.66549, 59.506413, 62.502884, 31...   
402997              49  [-57.977814, -44.80625, -24.183697, -19.802906...   
402998              56  [-165.79855, -105.64837, -23.280176, -35.18769...   

                                                  part_py  \
0       [-227.71448, -124.277214, -64.70931, -19.66986...   
1       [303.0099, 85.792786, 54.46955, 43.766777, 25....   
2       [93.24764, 46.335262, 36.74351, 24.203964, 33....   
3       [-9.679499, -7.6701407, -7.7122145, -6.91775, ...   
4       [-345.96057, -35.88268, -32.66261, -24.49807, ...   
...                                                   ...   
402994  [138.93217, 34.851875, 42.33146, 25.752123, 23...   
402995  [147.70444, 56.436275, 49.01416, 24.56699, 21....   
402996  [51.214066, 39.245872, 49.60018, 21.728268, 18...   
402997  [-137.3297, -56.038784, -35.9901, -28.894896, ...   
402998  [-74.01908, -66.62913, -39.13755, -21.93619, -...   

                                                  part_pz  \
0       [109.5397, 59.78943, 31.601667, 8.752145, 6.17...   
1       [-224.1275, -62.89838, -40.07812, -32.067, -9....   
2       [-22.612755, -49.185867, -37.796925, -5.251384...   
3       [-65.26732, -42.929283, -45.303036, -39.93612,...   
4       [103.54518, 10.739602, 9.883466, 7.613377, 3.7...   
...                                                   ...   
402994  [577.38226, 136.98364, 122.0693, 63.356335, 62...   
402995  [115.90381, 40.411144, 35.348694, 21.017828, 1...   
402996  [240.0167, 205.64616, 193.44537, 119.201294, 9...   
402997  [8.697165, 29.74873, 18.822954, 15.582845, 14....   
402998  [58.80575, 4.2255306, -9.37748, 1.1653519, 8.4...   

                                              part_energy  \
0       [266.67688, 145.65413, 76.116646, 22.791922, 1...   
1       [385.80774, 107.484184, 69.14874, 55.61113, 38...   
2       [144.53531, 70.963295, 56.28731, 37.790607, 50...   
3       [82.66848, 58.262596, 59.068157, 51.755386, 43...   
4       [406.58173, 42.170246, 36.417843, 27.428343, 1...   
...                                                   ...   
402994  [609.97266, 144.80074, 129.2024, 68.42321, 66....   
402995  [216.53705, 78.97798, 68.505646, 36.13991, 29....   
402996  [256.30936, 220.02092, 208.38019, 136.33662, 1...   
402997  [149.32016, 77.67195, 47.269886, 38.33921, 35....   
402998  [190.85623, 124.975494, 46.493565, 41.481663, ...

In [10]:
eta_cols = [col for col in df_val.columns if 'eta' in col]
pt_cols = [col for col in df_val.columns if 'pt' in col]    

In [27]:
import numpy as np
def get_pt_eta_phi_v(px, py, pz):
    '''Provides pt, eta, and phi given px, py, pz'''
    # Init variables
    pt = np.zeros(len(px))
    pt = np.sqrt(np.power(px,2) + np.power(py,2))
    phi = np.zeros(len(px))
    eta = np.zeros(len(px))
    theta = np.zeros(len(px))
    x = np.where((px!=0) | (py!=0) | (pz!=0)) # locate where px,py,pz are all 0 
    theta[x] = np.arctan2(pt[x],pz[x]) 
    cos_theta = np.cos(theta)
    y = np.where(np.power(cos_theta,2) < 1)
    eta[y] = -0.5*np.log((1 - cos_theta[y]) / (1 + cos_theta[y]))
    z = np.where((px !=0)|(py != 0))
    phi[z] = np.arctan2(py[z],px[z])
    return pt, eta, phi                     

(array([566.68309073,   0.        ]),
 array([0.42845257, 0.        ]),
 array([-1.20982244,  0.        ]))

In [37]:
sum(df['part_pz'][0])

250.2937389612198

In [ ]:
#Training and validation paths
train_path = '../../datasets/TopLandscape/val_file.parquet'
from pfn_dataset import PFNDataset
from torch.utils.data import DataLoader
train_set = PFNDataset(train_path)
trainloader = DataLoader(train_set, batch_size=500, shuffle=True, num_workers=30, pin_memory=True, persistent_workers=True)
for x,m,y in tqdm(trainloader):
    print(y.shape)

  9%|███████████▎                                                                                                                 | 36280/402999 [00:01<00:18, 19790.91it/s]

In [14]:
df.drop(columns=['truthE','truthPX','truthPY','truthPZ','ttv'])

E_0        PX_0        PY_0        PZ_0         E_1        PX_1  \
375  474.071136 -250.347031 -223.651962 -334.738098  103.236237  -48.866222   
377  150.504532  120.062393   76.852005  -48.274265   82.257057   63.801739   
378  251.645386   10.427651 -147.573746  203.564880  104.147797   10.718256   
379  451.566132  129.885437  -99.066292 -420.984100  208.410919   59.033958   
380  399.093903 -168.432083  -47.205597 -358.717438  273.691956 -121.926941   
..          ...         ...         ...         ...         ...         ...   
587  206.171997   13.942102  114.328499 -171.001465  231.602356   19.010832   
591  263.984161  -40.649391 -104.321312  239.065552  238.690689    8.786323   
592   61.417538   42.901291   43.947723   -0.436818   45.521763   31.723654   
593  261.215302   12.780115 -132.699203  224.635300  224.066376   52.028233   
596  221.000015  -32.458290 -127.960335 -177.238876  109.126007  -16.046606   

           PY_1        PZ_1         E_2       PX_2  ...  PZ_197  E_198  \
375  -56.790775  -71.025490  105.255569 -55.415001  ...     0.0    0.0   
377   42.754807  -29.454842   48.573559  36.763199  ...     0.0    0.0   
378  -54.497948   88.101395   78.043213   5.724113  ...     0.0    0.0   
379  -46.177090 -194.467941  190.183304  54.069675  ...     0.0    0.0   
380  -30.803854 -243.088928  152.837219 -44.400204  ...     0.0    0.0   
..          ...         ...         ...        ...  ...     ...    ...   
587   92.303848 -211.561432   95.868248   0.411594  ...     0.0    0.0   
591 -101.236137  215.979828  126.197868   5.939164  ...     0.0    0.0   
592   32.643845   -0.469300   44.801167  29.730831  ...     0.0    0.0   
593 -101.145271  193.050354   67.573616  17.166769  ...     0.0    0.0   
596  -62.676899  -87.878311  111.210052   0.395372  ...     0.0    0.0   

     PX_198  PY_198  PZ_198  E_199  PX_199  PY_199  PZ_199  is_signal_new  
375     0.0     0.0     0.0    0.0     0.0     0.0     0.0              0  
377     0.0     0.0     0.0    0.0     0.0     0.0     0.0              0  
378     0.0     0.0     0.0    0.0     0.0     0.0     0.0              0  
379     0.0     0.0     0.0    0.0     0.0     0.0     0.0              0  
380     0.0     0.0     0.0    0.0     0.0     0.0     0.0              0  
..      ...     ...     ...    ...     ...     ...     ...            ...  
587     0.0     0.0     0.0    0.0     0.0     0.0     0.0              1  
591     0.0     0.0     0.0    0.0     0.0     0.0     0.0              1  
592     0.0     0.0     0.0    0.0     0.0     0.0     0.0              1  
593     0.0     0.0     0.0    0.0     0.0     0.0     0.0              1  
596     0.0     0.0     0.0    0.0     0.0     0.0     0.0              1  

[1211000 rows x 801 columns]

In [42]:
import pandas as pd
df_train = pd.read_parquet('../../datasets/TopLandscape/train_file.parquet', engine='fastparquet')

In [77]:
import torch.nn.functional as F
source = np.arange(10)
# now we expand to size (7, 11) by appending a row of 0s at pos 0 and pos 6, 
# and a column of 0s at pos 10
result = F.pad(input=source, pad=(0, 80), mode='constant', value=0)


AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [4]:
from pfn_model import ParticleFlowNetwork
import torch
model = ParticleFlowNetwork().cuda()
x = torch.rand(500, 4, 200).cuda()
with torch.no_grad():
    y = model(x, None)
    print(y.shape)

torch.Size([500, 2])


In [5]:
import torch
f=torch.randn(1, 20)

In [6]:
print(f)
print(f.reshape(1, 5, 4))

tensor([[ 1.4071,  1.4981,  0.9273, -0.2600, -1.1360, -0.8745,  1.1853, -0.1428,
         -0.2028, -0.6146, -0.8889,  0.6755, -0.3049,  0.2580, -0.2100,  0.7883,
         -1.9270,  0.9030,  0.4163, -0.6080]])
tensor([[[ 1.4071,  1.4981,  0.9273, -0.2600],
         [-1.1360, -0.8745,  1.1853, -0.1428],
         [-0.2028, -0.6146, -0.8889,  0.6755],
         [-0.3049,  0.2580, -0.2100,  0.7883],
         [-1.9270,  0.9030,  0.4163, -0.6080]]])


In [86]:
df_train['mask'] = df_train['part_dphi'].apply(np.ones_like)

In [89]:
df_train['mask'][0][0:4]

array([1., 1., 1., 1.], dtype=float32)

In [38]:
pd.concat(pd.DataFrame(np.ones_like(df_train['part_deta'][1])), pd.DataFrame([0.0, 0.0]))

/tmp/ipykernel_134989/158974091.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  pd.concat(pd.DataFrame(np.ones_like(df_train['part_deta'][1])), pd.DataFrame([0.0, 0.0]))


TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [1]:
import torch
f = torch.randn((1, 4, 5))

In [2]:
g = f.permute(0, 2, 1)

In [3]:
f.shape

torch.Size([1, 4, 5])

In [4]:
g.shape

torch.Size([1, 5, 4])

In [5]:
h=torch.flatten(g, start_dim=0, end_dim=1)

In [6]:
h.shape

torch.Size([5, 4])

In [7]:
print(h)
print(f)

tensor([[-0.7160,  0.9192, -0.4916,  0.3304],
        [-1.0425,  0.5813, -1.4953, -0.6351],
        [ 0.3801, -0.3409, -1.2535,  0.8108],
        [-0.5252, -0.9671, -0.9845,  0.1875],
        [ 1.6481, -0.0755, -0.4311, -2.6189]])
tensor([[[-0.7160, -1.0425,  0.3801, -0.5252,  1.6481],
         [ 0.9192,  0.5813, -0.3409, -0.9671, -0.0755],
         [-0.4916, -1.4953, -1.2535, -0.9845, -0.4311],
         [ 0.3304, -0.6351,  0.8108,  0.1875, -2.6189]]])


In [25]:
torch.stack(torch.split(h.permute(1, 0), 3, dim=1), 0)

tensor([[[ 0.9418,  0.2681, -0.3037],
         [ 0.1757, -0.6186, -1.7090],
         [ 1.3164,  0.6942,  2.2612],
         [ 0.2935, -0.2816, -1.0366]],

        [[ 2.9455, -0.2199, -1.4355],
         [ 0.1163,  1.6256, -0.4481],
         [ 2.1020, -0.6185,  0.4537],
         [-0.3311, -0.1116,  1.0826]]])

In [14]:
j

tensor([[ 0.5396, -0.3306,  1.5733],
        [-1.4443,  0.4765,  0.3409],
        [-0.3215,  0.4200, -0.1825],
        [ 1.0658, -1.2802, -0.9324],
        [-0.1199,  0.9767, -0.4278],
        [-1.3017,  0.5196,  1.1094],
        [ 0.4849, -1.3108, -0.0366],
        [ 0.4450, -0.6639,  1.2869]])

In [15]:
f

tensor([[[ 0.5396, -1.4443, -0.3215,  1.0658],
         [-0.3306,  0.4765,  0.4200, -1.2802],
         [ 1.5733,  0.3409, -0.1825, -0.9324]],

        [[-0.1199, -1.3017,  0.4849,  0.4450],
         [ 0.9767,  0.5196, -1.3108, -0.6639],
         [-0.4278,  1.1094, -0.0366,  1.2869]]])

In [41]:
torch.stack(torch.split(j.permute(1, 0), 4, dim=1), 0)

tensor([[[ 0.5396, -1.4443, -0.3215,  1.0658],
         [-0.3306,  0.4765,  0.4200, -1.2802],
         [ 1.5733,  0.3409, -0.1825, -0.9324]],

        [[-0.1199, -1.3017,  0.4849,  0.4450],
         [ 0.9767,  0.5196, -1.3108, -0.6639],
         [-0.4278,  1.1094, -0.0366,  1.2869]]])

In [26]:
j.permute(1,0).shape

torch.Size([3, 8])

In [ ]:
from utils import accuracy
import torch
accuracy(torch.randn(3,2), torch.ones(1,3), topk=(1,2))

In [95]:
torch.randn(1,2).view(1,-1).expand_as(torch.randn(1,2))

tensor([[ 1.2675, -0.7427]])

In [96]:
f=torch.randn(1,2)